### ISSUE TITLE
Symlink the docker-compose file to root of project

### ISSUE THREAD

**Issue by drgomesp** [SymfonyDocker/DockerBundle#1]
We need to have a post-install command that will symlink the docker-compose file to the project root, for practicality purposes.

**Comment by thoroc** [comment]
+1

**Comment by drgomesp** [comment]
@thoroc want to jump in and open a PR? Should be quite straightforward. :)

**Comment by thoroc** [comment]
@drgomesp I need to look into post-install command for composer. I've never done anything this before. ;)

**Comment by herrkrieger** [comment]
Hi drgomesp,

running composer install ends with:

> composer install
> Loading composer repositories with package information
> Installing dependencies (including require-dev) from lock file
> Nothing to install or update
> Generating autoload files
> > Incenteev\ParameterHandler\ScriptHandler::buildParameters
> Updating the "app/config/parameters.yml" file
> > Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
> > Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache
> PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "DockerBundle" from namespace "Drgomesp\DockerBundle".
> Did you forget a "use" statement for another namespace? in /path/to/project/Symfony/01-symfony-docker/app/AppKernel.php:19
> Stack trace:
> #0 /path/to/project/Symfony/01-symfony-docker/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(396): AppKernel->registerBundles()
> #1 /path/to/project/Symfony/01-symfony-docker/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(114): Symfony\Component\HttpKernel\Kernel->initializeBundles()
> #2 /path/to/project/Symfony/01-symfony-docker/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(68): Symfony\Component\HttpKernel\Kernel->boot()
> #3 /path/to/project/Symfony/01-symfony-docker/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(117): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Co in /path/to/project/Symfony/01-symfony-docker/app/AppKernel.php on line 19
> Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the post-install-cmd event terminated with an exception
> 
>  
>   [RuntimeException]
>   An error occurred when executing the "'cache:clear --no-warmup'" command:
>   PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "DockerBundle" from namespace "Drgomesp\DockerBundle".
>   Did you forget a "use" statement for another namespace? in /path/to/project/Symfony/01-symfony-docker/app/AppKernel.php:19
>   Stack trace:
>   #0 /path/to/project/Symfony/01-symfony-docker/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(396): AppKernel->registerBundles()
>   #1 /path/to/project/Symfony/01-symfony-docker/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(114): Symfony\Component\HttpKernel\Kernel->init
>   ializeBundles()
>   #2 /path/to/project/Symfony/01-symfony-docker/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(68): Symfony\Component\HttpKerne
>   l\Kernel->boot()
>   #3 /path/to/project/Symfony/01-symfony-docker/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(117): Symfony\Bundle\FrameworkBundle\Console\
>   Application->doRun(Object(Symfony\Component\Co in /path/to/project/Symfony/01-symfony-docker/app/AppKernel.php on line 19
>   .
>  
> 
> install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--] [<packages>]...


System information:
cat /etc/lsb-release
DISTRIB_DESCRIPTION="Ubuntu 16.04.1 LTS

docker-compose -v
docker-compose version 1.9.0, build 2585387

docker info
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 22
Server Version: 1.12.4

sudo systemctl status docker
[sudo] Passwort für user1: 
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: active (running) since Di 2016-12-13 19:35:12 CET; 28min ago

Any idea, what I am doing wrong?
With kind regards

Hans

**Comment by drgomesp** [comment]
Can you show me your `AppKernel.php` file?
